name: ğŸš€ Deploy website on push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“‚ Sync Files
      uses: fifsky/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        user: ${{ secrets.SSH_USER }}
        pass: ${{ secrets.SSH_PASS }}
        args: "-tt"
        command: |
            cd /home/kodingke/short.kodingkeun.com
            ls -a
            cd /home/kodingke/short.kodingkeun.com && touch tmp/restart.txt
            exit 1
        
    # - name: â™»ï¸ Restart Server...
    #   uses: fifsky/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     port: ${{ secrets.SSH_PORT }}
    #     user: ${{ secrets.SSH_USER }}
    #     pass: ${{ secrets.SSH_PASS }}
    #     args: "-tt"
    #     command: cd /home/kodingke/short.kodingkeun.com && touch tmp/restart.txt

    - name: âœ… Telegram Notification Success
      uses: appleboy/telegram-action@master
      if: ${{ success() }}
      with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            âœ… `berhasil` *${{ github.actor }}* trigger deployment
            ğŸ“© Commit message: *${{ github.event.commits[0].message }}*
            ğŸ§‘â€ğŸ’» Developer: *${{github.actor}}*
            ğŸ”— See changes: [CEK APP](https://github.com/${{ github.repository }}/commit/${{github.sha}})
          format: markdown
          disable_web_page_preview: "True"

    - name: âŒ Telegram Notification Failed
      uses: appleboy/telegram-action@master
      if: ${{ failure() }}
      with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            âŒ `gagal` *${{ github.actor }}* trigger deployment
            ğŸ“© Commit message: *${{ github.event.commits[0].message }}*
            ğŸ§‘â€ğŸ’» Developer: *${{github.actor}}*
            ğŸ”— See changes: [CEK APP](https://github.com/${{ github.repository }}/commit/${{github.sha}})
          format: markdown
          disable_web_page_preview: "True"